"""
Pydantic schemas for request / response serialization.

Kept in a single file for now — split per-domain when it grows.
Schemas are deliberately decoupled from SQLAlchemy models so the
API surface can evolve independently of the DB layer.
"""

import uuid
from datetime import datetime, time
from enum import Enum

from pydantic import BaseModel, EmailStr, Field


# ── Auth ─────────────────────────────────────────────────────────────
class LoginRequest(BaseModel):
    email: str
    password: str
    device_id: str = Field(min_length=1, description="Persistent UUID generated by the client device")


class TokenResponse(BaseModel):
    access_token: str
    refresh_token: str
    token_type: str = "bearer"
    user_id: str
    roles: list[str]


class RefreshTokenRequest(BaseModel):
    refresh_token: str


class SessionOut(BaseModel):
    id: uuid.UUID
    device_id: str
    role: str
    created_at: datetime
    last_seen_at: datetime
    is_active: bool

    model_config = {"from_attributes": True}


class AcceptInvitationRequest(BaseModel):
    token: str
    password: str = Field(min_length=8)
    full_name: str


# ── User ─────────────────────────────────────────────────────────────
class UserOut(BaseModel):
    id: uuid.UUID
    email: str
    full_name: str
    phone: str | None = None
    address: str | None = None
    status: str
    roles: list[str] = []
    created_at: datetime

    model_config = {"from_attributes": True}


# ── Invitation ───────────────────────────────────────────────────────
class CreateInvitationRequest(BaseModel):
    email: str
    role_assigned: str


class InvitationOut(BaseModel):
    id: uuid.UUID
    email: str
    role_assigned: str
    token: str
    status: str
    expires_at: datetime
    created_at: datetime

    model_config = {"from_attributes": True}


# ── Warehouse ────────────────────────────────────────────────────────
class CreateWarehouseRequest(BaseModel):
    name: str
    address: str
    capacity: int | None = None


class UpdateWarehouseRequest(BaseModel):
    name: str | None = None
    address: str | None = None
    capacity: int | None = None


class WarehouseOut(BaseModel):
    id: uuid.UUID
    name: str
    address: str
    capacity: int | None = None
    created_at: datetime

    model_config = {"from_attributes": True}


# ── Operator Profile ────────────────────────────────────────────────
class OperatorProfileOut(BaseModel):
    user_id: uuid.UUID
    warehouse_id: uuid.UUID
    shift_start: time | None = None
    shift_end: time | None = None

    model_config = {"from_attributes": True}

class InvitationOutOperator(BaseModel):
    id: uuid.UUID
    email: str
    role_assigned: str
    token: str
    status: str
    expires_at: datetime
    created_at: datetime
    warehouses: list[WarehouseOut]

    model_config = {"from_attributes": True}


class AcceptInvitationRequestOperator(BaseModel):
    token: str
    password: str = Field(min_length=8)
    full_name: str
    warehouse_id: uuid.UUID
    shift_start: time | None = None
    shift_end: time | None = None

# ── Client ───────────────────────────────────────────────────────────
class ClientOut(BaseModel):
    id: uuid.UUID
    user_id: uuid.UUID
    company_name: str
    billing_address: str | None = None
    created_at: datetime

    model_config = {"from_attributes": True}

# ── Product / Inward ─────────────────────────────────────────────────
class ProductCreateRequest(BaseModel):
    """Step 1: create logical product (SKU definition only)."""
    name: str = Field(min_length=1, max_length=256)
    description: str | None = None
    category: str = Field(description="One of: FROZEN, CHILLED, DRY, PHARMA, OTHER")
    unit: str = Field(description="One of: KG, TON, BOX, PALLET, LITRE, UNIT")
    temperature_requirement: float | None = None
    warehouse_id: uuid.UUID


class InwardRequest(BaseModel):
    """Step 2: complete inward for an existing logical product."""

    product_id: uuid.UUID
    client_email: EmailStr
    rack_id: uuid.UUID
    quantity: float = Field(gt=0)
    lot_number: str = Field(min_length=1, max_length=128)
    warehouse_id: uuid.UUID


class ProductOut(BaseModel):
    id: uuid.UUID
    name: str
    description: str | None = None
    category: str
    unit: str
    temperature_requirement: float | None = None
    sku_code: str
    warehouse_id: uuid.UUID
    client_id: uuid.UUID | None = None
    client_email: str | None = None
    created_by: uuid.UUID
    created_at: datetime

    model_config = {"from_attributes": True}


class LinkClientResponse(BaseModel):
    detail: str
    client_linked: bool
    invitation_sent: bool
    product_id: uuid.UUID
    client_email: str


class InwardResponse(BaseModel):
    detail: str
    product_id: uuid.UUID
    ledger_id: uuid.UUID
    rack_allocation_id: uuid.UUID
    client_linked: bool
    invitation_sent: bool


# ── Inventory Analytics (read-only, ledger-derived) ────────────────
class InventoryDashboardOut(BaseModel):
    product_id: uuid.UUID
    product_name: str
    unit: str
    total_quantity: float
    warehouse_id: uuid.UUID
    has_lot_breakdown: bool


class InventoryLotStockOut(BaseModel):
    product_id: uuid.UUID
    lot_number: str
    inward_date: datetime
    current_quantity: float
    unit: str
    warehouse_id: uuid.UUID


class InventoryAgingOut(BaseModel):
    product_id: uuid.UUID
    lot_number: str
    inward_date: datetime
    aging_days: int
    current_quantity: float
    unit: str

# ── Password Reset / Change ──────────────────────────────────────────
class ForgotPasswordRequest(BaseModel):
    """User submits email to receive a 6-digit OTP."""
    email: EmailStr


class ResetPasswordRequest(BaseModel):
    """User submits the OTP received via email + new password."""
    email: EmailStr
    otp: str = Field(min_length=6, max_length=6, pattern=r"^\d{6}$")
    new_password: str = Field(min_length=8)


class ChangePasswordRequest(BaseModel):
    """Authenticated user changes their own password."""
    current_password: str
    new_password: str = Field(min_length=8)


# ── Room ─────────────────────────────────────────────────────────────
class TemperatureZoneCreateRequest(BaseModel):
    zone_name: str = Field(min_length=1, max_length=128)
    min_temp: float
    max_temp: float


class TemperatureZoneUpdateRequest(BaseModel):
    zone_name: str | None = Field(default=None, min_length=1, max_length=128)
    min_temp: float | None = None
    max_temp: float | None = None


class TemperatureZoneOut(BaseModel):
    id: uuid.UUID
    zone_name: str
    min_temp: float
    max_temp: float
    created_at: datetime

    model_config = {"from_attributes": True}


class CreateRoomRequest(BaseModel):
    name: str = Field(min_length=1, max_length=256)
    warehouse_id: uuid.UUID
    temperature_zone_id: uuid.UUID


class RoomOut(BaseModel):
    id: uuid.UUID
    name: str
    warehouse_id: uuid.UUID
    temperature_zone_id: uuid.UUID
    created_at: datetime

    model_config = {"from_attributes": True}


# ── Rack ─────────────────────────────────────────────────────────────
class CreateRackRequest(BaseModel):
    label: str = Field(min_length=1, max_length=128)
    room_id: uuid.UUID
    capacity: float = Field(gt=0)


class RackOut(BaseModel):
    id: uuid.UUID
    label: str
    room_id: uuid.UUID
    capacity: float
    is_occupied: bool
    created_at: datetime

    model_config = {"from_attributes": True}


# ── Rack Allocation ──────────────────────────────────────────────────
class RackAllocationOut(BaseModel):
    id: uuid.UUID
    rack_id: uuid.UUID
    sku_id: uuid.UUID
    allocated_by: uuid.UUID | None = None
    allocated_at: datetime
    released_at: datetime | None = None
    created_at: datetime

    model_config = {"from_attributes": True}


# ── Generic ──────────────────────────────────────────────────────────
class MessageResponse(BaseModel):
    detail: str
